### ISSUE TITLE
QA_Computer-Graphics_Hierarchical Transformations: 2D Demo_Objective_Spelling-mistakes

### ISSUE THREAD

**Issue by BSravanthi** [virtual-labs/computer-graphics-iiith#60]
Defect Description :
In the Objective  page of Hierarchical Transformations: 2D Demo experiment in the Computer Graphics lab, found spelling mistakes.

Actual Result :
In the Objective  page of Hierarchical Transformations: 2D Demo experiment in the Computer Graphics lab, found spelling mistakes.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Attachment:
![qa_oe_cg_i16](https://cloud.githubusercontent.com/assets/13479177/26104142/0f613816-3a5a-11e7-92ae-887d5804bcff.png)

**Comment by BSravanthi** [comment]
Fixed

**Comment by sravanthimodepu** [comment]
Issue is not yet fixed, still existing the same spelling. Hence reopening the issue.

**Comment by BSravanthi** [comment]
Fixed.
