### ISSUE TITLE
QA_Computer-Graphics_Hierarchical Transformations: 3D Articulated Arm_Theory_Spelling-mistakes 

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/computer-graphics-iiith#63]
Defect Description :
In the Theory page of Hierarchical Transformations: 3D Articulated Arm experiment in the Computer Graphics lab, found spelling mistakes.

Actual Result :
In the Theory page of Hierarchical Transformations: 3D Articulated Arm experiment in the Computer Graphics lab, found spelling mistakes.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Attachment:
![qa_oe_cg_i20](https://cloud.githubusercontent.com/assets/13479177/26140570/3857e030-3af5-11e7-9cd7-c09572a5aaed.png)

**Comment by BSravanthi** [comment]
Fixed

**Comment by sravanthimodepu** [comment]
Issue is not yet fixed, spelling mistake still exists in the theory.
