### ISSUE TITLE
QA_Computer-Graphics_Rasterization : Polygon_Introduction_Spelling-mistakes

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/computer-graphics-iiith#84]
Defect Description :
In the Introduction page of Rasterization : Polygon experiment in the Computer Graphics lab, found spelling mistakes.

Actual Result :
In the Introduction page of Rasterization : Polygon experiment in the Computer Graphics lab, found spelling mistakes.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Attachment:
![qa_oe_cg_i44](https://cloud.githubusercontent.com/assets/13479177/26151345/0b5ccd72-3b20-11e7-88cb-26b2bc5747c3.png)

**Comment by BSravanthi** [comment]
Fixed

**Comment by sravanthimodepu** [comment]
Issue is not yet fixed. Hence reopening the issue.
![rast-intro](https://user-images.githubusercontent.com/11156924/27761642-e8fc3368-5e7d-11e7-9b41-2991e93f0600.png)

**Comment by BSravanthi** [comment]
Fixed

**Comment by sravanthimodepu** [comment]
Closing..
