### ISSUE TITLE
QA_Computer-Graphics_Rasterization : Polygon_Objective_Spelling-mistakes

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/computer-graphics-iiith#85]
Defect Description :
In the Objective page of Rasterization : Polygon experiment in the Computer Graphics lab, found spelling mistakes.

Actual Result :
In the Objective page of Rasterization : Polygon experiment in the Computer Graphics lab, found spelling mistakes.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Attachment:
![qa_oe_cg_i45](https://cloud.githubusercontent.com/assets/13479177/26151509/d86112a6-3b20-11e7-8376-8cb9ea6a398c.png)

**Comment by BSravanthi** [comment]
Fixed

**Comment by sravanthimodepu** [comment]
Issue is not yet fixed. Hence reopening the issue.
![ply-obj](https://user-images.githubusercontent.com/11156924/27761620-7aa34eec-5e7d-11e7-8cde-363861201e60.png)

**Comment by BSravanthi** [comment]
Fixed

**Comment by sravanthimodepu** [comment]
Closing..
