### ISSUE TITLE
QA_Computer-Graphics_Rasterization : Polygon_Procedure_Spelling-mistakes 

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/computer-graphics-iiith#87]
Defect Description :
In the Procedure page of Rasterization : Polygon experiment in the Computer Graphics lab, found spelling mistakes.

Actual Result :
In the Procedure page of Rasterization : Polygon experiment in the Computer Graphics lab, found spelling mistakes.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Attachment:
![qa_oe_cg_i48](https://cloud.githubusercontent.com/assets/13479177/26151748/bee5846e-3b21-11e7-9d8c-2cf2eccbbdc0.png)

**Comment by BSravanthi** [comment]
Fixed

**Comment by sravanthimodepu** [comment]
Issue is not yet fixed. Hence reopening the issue.
![rast-poly](https://user-images.githubusercontent.com/11156924/27761538-4f28d1da-5e7b-11e7-98db-decd1d5616b7.png)

**Comment by BSravanthi** [comment]
Fixed

**Comment by sravanthimodepu** [comment]
Closing..
